language: php 
php: 
 - 5.3
notifications:
  email:
    - devs@webbuildersgroup.com

env:
 - DB=MYSQL CORE_RELEASE=3.0
 - DB=PGSQL CORE_RELEASE=3.0
 - DB=SQLITE3 CORE_RELEASE=3.0

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - php ~/translatablerouting/tests/pre-up/travis_setup.php
 - cd ~/builds/ss

script: 
 - phpunit translatablerouting/tests/